### ISSUE TITLE
combination basis error with GLM

### ISSUE THREAD

**Issue by MushroomHunting** [NICTA/revrand#109]
Hey guys,

Trying the GLM with some combination basis functions, when the basis is a BasicCat object with more than one basis function, there is an error 

**AttributeError: 'list' object has no attribute 'value'**

in glm.py line 324 ( https://github.com/NICTA/revrand/blob/master/revrand/glm.py#L324 )

debugging this shows glm's self.basis.params as a list of parameters and not just one. Changing that line to something like `bpars = [o.value for o in self.basis.params ]` appears to work however this doesn't work if there is a value parameter if any one of the Basis objects .value is a list. I'm not sure the exact format and order required by `bpars` in this case, but perhaps one could use `bpars = chain.from_iterable( [o.value for o in self.basis.params ] )`

for reference, my basis function is defined similar to 
`base_1 = bf.RandomRBF(nbases=n_bases, Xdim=X_train.shape[1], lenscale_init=len_2)`
`base_2 = bf.RandomRBF(nbases=n_bases, Xdim=X_train.shape[1], lenscale_init=len_3)`
`base_3 = bf.RandomRBF(nbases=n_bases, Xdim=X_train.shape[1], lenscale_init=len_4)`
`base = base_1 + base_2 + base_3`

**Comment by dsteinberg** [comment]
Thanks for pointing this out Anthony!

This is something I put in recently, and somehow it's not covered in the unit tests! How did you create `len_2`, `len_3` and `len_4` in your example?

BTW, the GLM is undergoing some pretty drastic changes. I'm changing it over from nonparametric variational inference to Auto-encoding VB. So far it seems superior, and simplifies the code dramatically.

**Comment by MushroomHunting** [comment]
Hey Dan,

`len_2` etc were just defined like 'Parameter(1., Positive())` 
Thanks for the heads up on the changes!

Anth

**Comment by dsteinberg** [comment]
Ok, this is fixed in master, see 99c2a37
