### ISSUE TITLE
problems with demos

### ISSUE THREAD

**Issue by AIAdventures** [NICTA/revrand#131]
Hi,
Just trying to run through some of the demos and get the below error.
![screenshot_2017-06-05_13-40-57](https://cloud.githubusercontent.com/assets/26102503/26769754/bb8ad92c-49f4-11e7-960a-e9cdbef44861.png)

**Comment by AIAdventures** [comment]
Jupyter Notebook Logout reparameterization_trick demo

**Comment by dsteinberg** [comment]
See if the latest commit to master fixes this notebook, there were a few incorrectly named variables. Re-open if this is still an issue, thanks for finding this problem.

**Comment by AIAdventures** [comment]
cheers mate, awesome library!

**Comment by AIAdventures** [comment]
will run some more checks :)
