### ISSUE TITLE
Positive() does not pickle nicely

### ISSUE THREAD

**Issue by dsteinberg** [NICTA/revrand#31]
Before putting the `*args` parameter into `Positive.__new__()`

```
from revrand import likelihoods
import pickle as pkl

gaus = likelihoods.Gaussian()
pgs = pkl.dumps(gaus)
reg = pkl.loads(pgs)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-e387820c5f0b> in <module>()
----> 1 pkl.loads(pgs)

TypeError: __new__() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by dtpc** [comment]
I came across this as well as Spark pickles variables to broadcast them to the workers. My solution after some googling was to implement `__getnewargs__()` which is called before pickling. See: e9ee473fc1f945a85b854a80b34b6326ba1a6f43

**Comment by dsteinberg** [comment]
Thanks @dtpc, I've cherry-picked your fix since it was nicer than what we did!
