### ISSUE TITLE
Optimizer abstraction

### ISSUE THREAD

**Issue by ltiao** [NICTA/revrand#4]
Optimizer should infer which classifier backend to use based on the method. If the method lies in the intersection of the set of methods supported by two or more backends, allow user to choose which backend. Backend should be `scipy.optimize` by default.

**Comment by dsteinberg** [comment]
Let's see what happens with autograd (#37) and whether we can remove nlopt before committing to this.

**Comment by dsteinberg** [comment]
I think we should remove NLopt totally....
