### ISSUE TITLE
Compare auto gradient values agains explicit gradients

### ISSUE THREAD

**Issue by ltiao** [NICTA/revrand#47]

**Comment by ltiao** [comment]
Compared `autograd` values with @dsteinberg-`grad` values for ELBO w.r.t. hyperparameters variance, regulariser and RBF lenscale, and accurate to `1e-10`.

**Comment by ltiao** [comment]
@dsteinberg can probably be deprecated in next major release :p

**Comment by dsteinberg** [comment]
:-(
