### ISSUE TITLE
Look into autograd with learn_sgd

### ISSUE THREAD

**Issue by ltiao** [NICTA/revrand#70]

**Comment by RansML** [comment]
I used it yesterday to learn a logistic regression classifier with elasticnet using SGD. There were around 1000 parameters. 
It was straightforward to use and fast enough. Broadcasting is bit tricky. https://github.com/HIPS/autograd/blob/master/docs/tutorial.md#supported-and-unsupported-parts-of-numpyscipy

I have also put my code in cython and haven't faced any issues so far.

**Comment by ltiao** [comment]
learn_sgd is now deprecated. Closing this issue.
